import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navigation from "@/components/Navigation";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={`${inter.className} antialiased bg-gray-50`}>
        <Navigation />
        {/* Main Content Wrapper: Left Margin for Sidebar on Desktop, Bottom Padding for Nav on Mobile */}
        <main className="md:ml-64 transition-all duration-300 min-h-screen pb-16 md:pb-0">
          {children}
        </main>
      </body>
    </html>
  );
}
